vich_uploader:
    db_driver: orm
    mappings:
        place_image:
            uri_prefix: /photos/downloads
            upload_destination: '%kernel.project_dir%/public/photos/downloads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        source_file:
            uri_prefix: /files/downloads
            upload_destination: '%kernel.project_dir%/public/files/downloads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
