vich_uploader:
    db_driver: orm
    mappings:
        place_image:
            uri_prefix: /files/places
            upload_destination: '%kernel.project_dir%/public/files/places'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        source_file:
            uri_prefix: /files/sources
            upload_destination: '%kernel.project_dir%/public/files/sources'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
